# frozen_string_literal: true

# rbs_inline: enabled

module SpecToPbt
  class StatefulGenerator
    # Renders the generated runtime helper module embedded in the scaffold.
    class SupportModuleRenderer
      # @rbs generator: StatefulGenerator
      # @rbs return: void
      def initialize(generator)
        @generator = generator
      end

      # @rbs return: Array[String]
      def render_lines
        [
          "  module #{support_module_name}",
          "    module_function",
          "    ARGUMENTS_OVERRIDE_UNSET = Object.new.freeze",
          "",
          "    KNOWN_TOP_LEVEL_KEYS = %i[sut_factory initial_state command_mappings verify_context before_run after_run state_reader].freeze",
          "    KNOWN_COMMAND_KEYS = %i[method arg_adapter model_arg_adapter result_adapter arguments_override applicable_override next_state_override verify_override guard_failure_policy].freeze",
          "",
          "    def config",
          "      defined?(::#{config_constant_name}) ? ::#{config_constant_name} : {}",
          "    end",
          "",
          "    def validate_config!",
          "      return if config.empty?",
          "",
          "      unknown_top = config.keys - KNOWN_TOP_LEVEL_KEYS",
          "      raise \"Unknown config keys in #{config_constant_name}: \#{unknown_top.inspect}. See docs/config-reference.md for valid keys.\" unless unknown_top.empty?",
          "",
          "      config.fetch(:command_mappings, {}).each do |cmd_name, cmd_config|",
          "        next unless cmd_config.is_a?(Hash)",
          "        unknown_cmd = cmd_config.keys - KNOWN_COMMAND_KEYS",
          "        raise \"Unknown config keys in #{config_constant_name} command_mappings[\#{cmd_name}]: \#{unknown_cmd.inspect}. See docs/config-reference.md for valid keys.\" unless unknown_cmd.empty?",
          "      end",
          "",
          "      if !config.key?(:sut_factory)",
          "        warn \"Warning: #{config_constant_name} is missing :sut_factory (required). The scaffold will use a default factory.\"",
          "      end",
          "",
          "      if state_reader.nil?",
          "        warn \"Warning: #{config_constant_name} has no verify_context.state_reader configured. SUT state will not be compared against the model.\"",
          "      end",
          "    end",
          "",
          "    def sut_factory(default_factory)",
          "      config.fetch(:sut_factory, default_factory)",
          "    end",
          "",
          "    def initial_state(default_state)",
          "      config.fetch(:initial_state, default_state)",
          "    end",
          "",
          "    def command_config(command_name)",
          "      config.fetch(:command_mappings, {}).fetch(command_name, {})",
          "    end",
          "",
          "    def arguments_override(command_name)",
          "      command_config(command_name)[:arguments_override]",
          "    end",
          "",
          "    def call_arguments_override(command_name, state = ARGUMENTS_OVERRIDE_UNSET)",
          "      override = arguments_override(command_name)",
          "      return ARGUMENTS_OVERRIDE_UNSET unless override",
          "",
          "      parameters = override.parameters",
          "      if parameters.any? { |kind, _name| kind == :rest }",
          "        return state.equal?(ARGUMENTS_OVERRIDE_UNSET) ? override.call : override.call(state)",
          "      end",
          "",
          "      required = parameters.count { |kind, _name| kind == :req }",
          "      optional = parameters.count { |kind, _name| kind == :opt }",
          "      provided = state.equal?(ARGUMENTS_OVERRIDE_UNSET) ? 0 : 1",
          "",
          "      if provided >= required && provided <= required + optional",
          "        return provided.zero? ? override.call : override.call(state)",
          "      end",
          "",
          "      if 0 >= required && 0 <= required + optional",
          "        return override.call",
          "      end",
          "",
          "      raise ArgumentError, \"arguments_override for command \#{command_name.inspect} must accept 0 or 1 positional arguments\"",
          "    end",
          "",
          "    def resolve_method_name(command_name, default_method_name)",
          "      command_config(command_name).fetch(:method, default_method_name)",
          "    end",
          "",
          "    def adapt_args(command_name, args)",
          "      settings = command_config(command_name)",
          "      adapter = settings[:arg_adapter] || settings[:model_arg_adapter]",
          "      adapter ? adapter.call(args) : args",
          "    end",
          "",
          "    def model_args(command_name, args)",
          "      adapter = command_config(command_name)[:model_arg_adapter] || command_config(command_name)[:arg_adapter]",
          "      adapter ? adapter.call(args) : args",
          "    end",
          "",
          "    def scalar_model_arg(command_name, args)",
          "      payload = model_args(command_name, args)",
          "      payload.is_a?(Array) && payload.length == 1 ? payload.first : payload",
          "    end",
          "",
          "    def adapt_result(command_name, result)",
          "      adapter = command_config(command_name)[:result_adapter]",
          "      adapter ? adapter.call(result) : result",
          "    end",
          "",
          "    def applicable_override(command_name)",
          "      command_config(command_name)[:applicable_override]",
          "    end",
          "",
          "    def next_state_override(command_name)",
          "      command_config(command_name)[:next_state_override]",
          "    end",
          "",
          "    def guard_failure_policy(command_name)",
          "      command_config(command_name)[:guard_failure_policy]",
          "    end",
          "",
          "    def call_applicable_override(override, state, args)",
          "      parameters = override.parameters",
          "      if parameters.any? { |kind, _name| kind == :rest }",
          "        override.call(state, args)",
          "      else",
          "        required = parameters.count { |kind, _name| kind == :req }",
          "        optional = parameters.count { |kind, _name| kind == :opt }",
          "        if 2 >= required && 2 <= required + optional",
          "          override.call(state, args)",
          "        elsif 1 >= required && 1 <= required + optional",
          "          override.call(state)",
          "        else",
          "          override.call",
          "        end",
          "      end",
          "    end",
          "",
          "    def call_next_state_override(override, state, args)",
          "      return nil unless override",
          "",
          "      parameters = override.parameters",
          "      if parameters.any? { |kind, _name| kind == :rest }",
          "        override.call(state, args)",
          "      else",
          "        required = parameters.count { |kind, _name| kind == :req }",
          "        optional = parameters.count { |kind, _name| kind == :opt }",
          "        if 2 >= required && 2 <= required + optional",
          "          override.call(state, args)",
          "        elsif 1 >= required && 1 <= required + optional",
          "          override.call(state)",
          "        else",
          "          override.call",
          "        end",
          "      end",
          "    end",
          "",
          "    def verify_override(command_name)",
          "      command_config(command_name)[:verify_override]",
          "    end",
          "",
          "    def state_reader",
          "      config.fetch(:verify_context, {})[:state_reader] || config[:state_reader]",
          "    end",
          "",
          "    def observed_state(sut)",
          "      reader = state_reader",
          "      reader ? reader.call(sut) : nil",
          "    end",
          "",
          "    def call_verify_override(command_name, **kwargs)",
          "      override = verify_override(command_name)",
          "      return false unless override",
          "",
          "      payload = kwargs.merge(observed_state: observed_state(kwargs[:sut]))",
          "      if override.parameters.any? { |kind, _name| kind == :keyrest }",
          "        override.call(**payload)",
          "      else",
          "        accepted = override.parameters.filter_map do |kind, name|",
          "          name if [:keyreq, :key].include?(kind)",
          "        end",
          "        accepted_payload = accepted.empty? ? {} : payload.select { |key, _value| accepted.include?(key) }",
          "        override.call(**accepted_payload)",
          "      end",
          "      true",
          "    end",
          "",
          "    def before_run_hook",
          "      config[:before_run]",
          "    end",
          "",
          "    def after_run_hook",
          "      config[:after_run]",
          "    end",
          "  end"
        ]
      end

      private

      # @rbs return: String
      def support_module_name
        @generator.__send__(:support_module_name)
      end

      # @rbs return: String
      def config_constant_name
        @generator.__send__(:config_constant_name)
      end
    end
  end
end
